mod common;

use common::*;

#[test]
fn manage_instructions_doctor_and_task_create_form_one_workflow() {
    let fixture = GitFixture::new();
    fixture.clone_shared();

    let dry = workspace(
        &fixture.shared,
        [
            "manage",
            "--dry-run",
            "--repo",
            fixture.shared.to_str().unwrap(),
        ],
    );
    assert_eq!(json(&dry)["status"], "dry_run");
    assert!(!fixture.shared.join(".workspace-mgr.toml").exists());
    assert!(
        !fixture
            .shared
            .join(".workspace-mgr/local/repository.lock")
            .exists()
    );

    let initialized = workspace(
        &fixture.shared,
        ["manage", "--repo", fixture.shared.to_str().unwrap()],
    );
    assert_eq!(json(&initialized)["status"], "managed");
    assert!(fixture.shared.join(".workspace-mgr.toml").is_file());
    assert!(fixture.shared.join("AGENTS.md").is_file());
    let root_ignore = std::fs::read_to_string(fixture.shared.join(".gitignore")).unwrap();
    assert!(root_ignore.starts_with("# Generated by workspace-mgr."));
    assert!(root_ignore.contains(".workspace-mgr/repository.gitignore"));
    assert!(root_ignore.contains("\n.DS_Store\n"));
    assert!(root_ignore.contains("\nnode_modules/\n"));

    let repeated = workspace(
        &fixture.shared,
        ["manage", "--repo", fixture.shared.to_str().unwrap()],
    );
    assert_eq!(json(&repeated)["status"], "no_changes");

    let instructions = workspace(&fixture.shared, ["--format", "human", "instructions"]);
    let text = String::from_utf8(instructions.stdout).unwrap();
    let model = text.find("# How this workspace works").unwrap();
    let rules = text.find("# Effective repository instructions").unwrap();
    assert!(
        model < rules,
        "management model must precede operational rules"
    );
    let normalized_text = text.split_whitespace().collect::<Vec<_>>().join(" ");
    for global in [
        "one writable conversation (chat) = one task",
        "Effective repository instructions",
        "shared checkout",
        "Reading and ownership are separate",
        "default write boundary is its own task directory",
        "another chat's task directory",
        "explicit user authorization for the exact path and action",
        "do not manufacture it",
        "cloud-usage approval, CLI installation and updates",
        "before every writable-task turn",
        "task create --help",
        "archive --help",
        "policy=",
    ] {
        assert!(
            normalized_text.contains(global),
            "global instructions omit {global:?}"
        );
    }
    assert!(
        text.len() < 10_000,
        "default output grew into an operation manual"
    );
    for operation_detail in [
        "## Task lifecycle",
        "## Publication",
        "## Artifact hygiene",
        "## Storage placement",
        "## Repository infrastructure",
        "--historical-record",
        "small-s3-boundary",
        "source retirement",
        "1.25 GiB (1342177280 bytes)",
    ] {
        assert!(
            !text.contains(operation_detail),
            "default output leaked {operation_detail:?}"
        );
    }
    let explicit_all = workspace(
        &fixture.shared,
        ["--format", "human", "instructions", "all"],
    );
    assert_eq!(explicit_all.stdout, text.as_bytes());

    let model_only = workspace(
        &fixture.shared,
        ["--format", "human", "instructions", "model"],
    );
    let model_only = String::from_utf8(model_only.stdout).unwrap();
    assert!(model_only.contains("# How this workspace works"));
    assert!(!model_only.contains("# Effective repository instructions"));

    let doctor = workspace(&fixture.shared, ["--format", "json", "doctor"]);
    assert_eq!(json(&doctor)["status"], "ok");

    let created = workspace(
        &fixture.shared,
        [
            "task",
            "create",
            "sample-task",
            "--title",
            "Sample task",
            "--purpose",
            "Exercise deterministic scaffolding.",
            "--timestamp",
            "20260829-170000",
        ],
    );
    let payload = json(&created);
    assert_eq!(payload["status"], "created");
    assert_eq!(payload["task_id"], "20260829-170000-sample-task");
    assert_eq!(payload["review"]["pull_request"], "required");
    assert_eq!(
        payload["review"]["creation_timing"],
        "immediate-after-scaffold-publication"
    );
    assert_eq!(
        payload["review"]["synchronization_cadence"],
        "before-every-turn-end"
    );
    let task = fixture.shared.join("20260829-170000-sample-task");
    assert!(task.join("README.md").is_file());
    assert!(task.join(".workspace-mgr-task.toml").is_file());
    assert_eq!(
        payload["files"].as_array().unwrap(),
        &vec![
            serde_json::json!("20260829-170000-sample-task/README.md"),
            serde_json::json!("20260829-170000-sample-task/.workspace-mgr-task.toml"),
        ]
    );
    let readme = std::fs::read_to_string(task.join("README.md")).unwrap();
    assert!(readme.contains("## Directory map"));
    assert!(readme.contains(
        "- Keep this task's tools, process, decisions, and hard-to-reproduce results in this directory and list them here."
    ));
    let branch = git(
        &fixture.shared,
        ["rev-parse", "--verify", "codex/sample-task"],
    );
    assert!(!branch.stdout.is_empty());
}

#[test]
fn infrastructure_task_publishes_from_main_with_private_state_and_index() {
    let fixture = GitFixture::new();
    workspace(&fixture.seed, ["manage"]);
    fixture.commit_seed("Add workspace policy");
    fixture.clone_shared();

    let created = workspace(
        &fixture.shared,
        [
            "task",
            "create",
            "shared-policy",
            "--kind",
            "infrastructure",
            "--title",
            "Shared policy",
            "--purpose",
            "Update one repository-wide policy file.",
            "--scope",
            "shared-policy.md",
            "--scope-note",
            "The user requested this repository-wide policy change.",
        ],
    );
    let created = json(&created);
    assert_eq!(created["kind"], "infrastructure");
    assert_eq!(created["task_id"], "infra-shared-policy");
    assert_eq!(created["branch"], "codex/infra-shared-policy");
    assert_eq!(
        created["review"]["creation_timing"],
        "after-first-scoped-publication"
    );
    assert_eq!(
        created["review"]["synchronization_cadence"],
        "before-every-turn-end"
    );
    let worktree = std::path::PathBuf::from(created["path"].as_str().unwrap());
    let manifest = std::path::PathBuf::from(created["manifest"].as_str().unwrap());
    assert_eq!(worktree, fixture.shared.canonicalize().unwrap());
    assert!(worktree.is_dir());
    assert!(manifest.is_file());
    assert!(!fixture.shared.join("infra-shared-policy").exists());
    assert_eq!(
        String::from_utf8_lossy(&git(&worktree, ["branch", "--show-current"]).stdout).trim(),
        "main"
    );
    let main_before = git(&worktree, ["rev-parse", "HEAD"]).stdout;
    let index_before = git(&worktree, ["ls-files", "--stage"]).stdout;
    let worktrees_before = git(&worktree, ["worktree", "list", "--porcelain"]).stdout;
    let unselected = workspace_unchecked(&worktree, ["task", "status"]);
    assert_eq!(
        unselected.status.code(),
        Some(2),
        "private infrastructure tasks require explicit selection"
    );

    let status = workspace(
        &worktree,
        ["task", "status", "--manifest", manifest.to_str().unwrap()],
    );
    assert_eq!(json(&status)["kind"], "infrastructure");
    assert_eq!(
        json(&status)["scopes"],
        serde_json::json!(["shared-policy.md"])
    );
    let explicit = workspace(
        &fixture.shared,
        ["task", "status", "--manifest", manifest.to_str().unwrap()],
    );
    assert_eq!(json(&explicit)["branch"], "codex/infra-shared-policy");
    let doctor = workspace(&worktree, ["doctor"]);
    assert_eq!(json(&doctor)["status"], "ok");
    std::fs::write(worktree.join("shared-policy.md"), "shared policy\n").unwrap();
    std::fs::write(
        worktree.join("unrelated-overlay.txt"),
        "another task's unpublished bytes\n",
    )
    .unwrap();
    let published = workspace(
        &worktree,
        [
            "publish",
            "--manifest",
            manifest.to_str().unwrap(),
            "-m",
            "Publish shared policy",
        ],
    );
    let published = json(&published);
    assert_eq!(published["status"], "pushed");
    assert_eq!(published["head"], "main");
    assert_eq!(published["review"]["pull_request"], "required");
    assert_eq!(published["review"]["managed_by"], "agent");
    assert_eq!(published["review"]["merge_authority"], "user");
    assert_eq!(git(&worktree, ["rev-parse", "HEAD"]).stdout, main_before);
    assert_eq!(git(&worktree, ["ls-files", "--stage"]).stdout, index_before);
    assert_eq!(
        git(&worktree, ["worktree", "list", "--porcelain"]).stdout,
        worktrees_before
    );
    let commit = published["commit_oid"].as_str().unwrap();
    assert!(
        git_unchecked(
            &fixture.shared,
            ["cat-file", "-e", &format!("{commit}:shared-policy.md")],
        )
        .status
        .success()
    );
    assert!(
        !git_unchecked(
            &worktree,
            ["cat-file", "-e", &format!("{commit}:unrelated-overlay.txt")]
        )
        .status
        .success()
    );
    assert_eq!(
        std::fs::read_to_string(worktree.join("unrelated-overlay.txt")).unwrap(),
        "another task's unpublished bytes\n"
    );

    std::fs::remove_file(worktree.join("shared-policy.md")).unwrap();
    let removed = workspace(
        &worktree,
        [
            "publish",
            "--manifest",
            manifest.to_str().unwrap(),
            "-m",
            "Remove shared policy",
        ],
    );
    let removed = json(&removed);
    assert_eq!(removed["status"], "pushed");
    assert_eq!(
        removed["changed_paths"],
        serde_json::json!(["shared-policy.md"])
    );
    let removed_commit = removed["commit_oid"].as_str().unwrap();
    assert!(
        !git_unchecked(
            &fixture.shared,
            [
                "cat-file",
                "-e",
                &format!("{removed_commit}:shared-policy.md")
            ],
        )
        .status
        .success()
    );
    let clean = workspace(
        &worktree,
        ["plan", "--manifest", manifest.to_str().unwrap()],
    );
    assert_eq!(json(&clean)["status"], "no_changes");
}

#[test]
fn infrastructure_plan_and_publish_require_main_refresh_before_replacing_upstream_scopes() {
    let fixture = GitFixture::new();
    workspace(&fixture.seed, ["manage"]);
    std::fs::write(fixture.seed.join("policy.md"), "original upstream policy\n").unwrap();
    fixture.commit_seed("Initialize shared policy");
    fixture.clone_shared();
    let created = json(&workspace(
        &fixture.shared,
        [
            "task",
            "create",
            "change-policy",
            "--kind",
            "infrastructure",
            "--title",
            "Change shared policy",
            "--purpose",
            "Protect concurrent shared-policy changes",
            "--scope",
            "policy.md",
            "--scope-note",
            "The user requested this shared policy change",
        ],
    ));
    let manifest = created["manifest"].as_str().unwrap();
    std::fs::write(fixture.shared.join("policy.md"), "local proposed policy\n").unwrap();
    let main_before = git(&fixture.shared, ["rev-parse", "HEAD"]).stdout;
    let index_before = git(&fixture.shared, ["ls-files", "--stage"]).stdout;
    std::fs::write(
        fixture.seed.join("policy.md"),
        "concurrent upstream policy\n",
    )
    .unwrap();
    fixture.commit_seed("Update policy before infrastructure publication");
    for args in [
        vec!["plan", "--manifest", manifest],
        vec![
            "publish",
            "--manifest",
            manifest,
            "-m",
            "Attempt to publish stale policy",
        ],
    ] {
        let refused = workspace_unchecked(&fixture.shared, args);
        assert_eq!(refused.status.code(), Some(2));
        assert!(String::from_utf8_lossy(&refused.stderr).contains("refresh"));
        assert_eq!(
            git(&fixture.shared, ["rev-parse", "HEAD"]).stdout,
            main_before
        );
        assert_eq!(
            git(&fixture.shared, ["ls-files", "--stage"]).stdout,
            index_before
        );
        assert_eq!(
            std::fs::read_to_string(fixture.shared.join("policy.md")).unwrap(),
            "local proposed policy\n"
        );
        assert!(
            !git_unchecked(
                &fixture.remote,
                [
                    "show-ref",
                    "--verify",
                    "refs/heads/codex/infra-change-policy"
                ]
            )
            .status
            .success()
        );
        assert_eq!(
            String::from_utf8(git(&fixture.remote, ["show", "main:policy.md"]).stdout).unwrap(),
            "concurrent upstream policy\n"
        );
    }
}

#[test]
fn setup_verifies_native_storage_without_python_or_directory_changes() {
    let fixture = GitFixture::new();
    let runtime = fixture.root.join("former-runtime");
    std::fs::create_dir(&runtime).unwrap();
    std::fs::write(runtime.join("sentinel"), "preserve\n").unwrap();
    for dry_run in [true, false] {
        let mut args = vec!["setup", "--runtime-dir", runtime.to_str().unwrap()];
        if dry_run {
            args.push("--dry-run");
        }
        let output = binary_command()
            .args(args)
            .current_dir(&fixture.root)
            .env("WORKSPACE_MGR_FORMAT", "json")
            .env("WORKSPACE_MGR_BOOTSTRAP_PYTHON", "/does-not-exist/python")
            .env("WORKSPACE_MGR_STORAGE_DVC", "/does-not-exist/dvc")
            .env("WORKSPACE_MGR_STORAGE_PYTHON", "/does-not-exist/python")
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        let report = json(&output);
        assert_eq!(
            report["storage_runtime"],
            format!("native Rust {}", env!("CARGO_PKG_VERSION"))
        );
        assert_eq!(report["runtime_dir"], "");
        assert_eq!(
            std::fs::read_to_string(runtime.join("sentinel")).unwrap(),
            "preserve\n"
        );
        assert_eq!(std::fs::read_dir(&runtime).unwrap().count(), 1);
    }
}

#[test]
fn first_manage_preserves_foreign_agents_and_recovers_a_missing_config() {
    let fixture = GitFixture::new();
    fixture.clone_shared();
    let agents_path = fixture.shared.join("AGENTS.md");
    std::fs::write(&agents_path, "# Repository-owned instructions\n").unwrap();
    let rejected = workspace_unchecked(&fixture.shared, ["manage"]);
    assert_eq!(rejected.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&rejected.stderr).contains("AGENTS.md"));
    assert_eq!(
        std::fs::read_to_string(&agents_path).unwrap(),
        "# Repository-owned instructions\n"
    );
    assert!(!fixture.shared.join(".workspace-mgr.toml").exists());

    std::fs::remove_file(&agents_path).unwrap();
    workspace(&fixture.shared, ["manage"]);
    let canonical = std::fs::read_to_string(&agents_path).unwrap();
    assert!(canonical.contains("install the latest stable release"));
    assert!(canonical.contains("    cargo install --locked workspace-mgr\n"));
    assert!(!canonical.contains("cargo install --locked workspace-mgr --version"));
    assert!(canonical.contains("workspace-mgr setup"));
    assert!(canonical.contains("retry `workspace-mgr instructions --repo .`"));
    std::fs::remove_file(fixture.shared.join(".workspace-mgr.toml")).unwrap();
    workspace(&fixture.shared, ["manage"]);
    assert_eq!(std::fs::read_to_string(&agents_path).unwrap(), canonical);
    assert!(fixture.shared.join(".workspace-mgr.toml").is_file());
}

#[test]
fn manage_reconciles_the_owned_agents_bootstrap_regardless_of_content() {
    let fixture = GitFixture::new();
    fixture.clone_shared();
    workspace(&fixture.shared, ["manage"]);
    let agents_path = fixture.shared.join("AGENTS.md");
    let canonical = std::fs::read_to_string(&agents_path).unwrap();

    std::fs::write(&agents_path, "# Legacy or locally edited bootstrap\n").unwrap();
    let unhealthy = workspace_unchecked(&fixture.shared, ["doctor"]);
    assert_eq!(unhealthy.status.code(), Some(2));
    let report = json(&unhealthy);
    assert!(report["checks"].as_array().unwrap().iter().any(|check| {
        check["name"] == "repository-scaffold"
            && check["status"] == "error"
            && check["detail"].as_str().unwrap().contains("AGENTS.md")
    }));
    let updated = workspace(&fixture.shared, ["manage"]);
    assert_eq!(json(&updated)["status"], "managed");
    assert_eq!(json(&updated)["actions"][0]["action"], "update");
    assert_eq!(json(&updated)["actions"][0]["path"], "AGENTS.md");
    assert_eq!(std::fs::read_to_string(&agents_path).unwrap(), canonical);

    std::fs::remove_file(&agents_path).unwrap();
    let recreated = workspace(&fixture.shared, ["manage"]);
    assert_eq!(json(&recreated)["status"], "managed");
    assert_eq!(json(&recreated)["actions"][0]["action"], "create");
    assert_eq!(std::fs::read_to_string(&agents_path).unwrap(), canonical);
}

#[test]
fn repository_configuration_cannot_change_the_workspace_policy() {
    let fixture = GitFixture::new();
    fixture.clone_shared();
    workspace(&fixture.shared, ["manage"]);

    let path = fixture.shared.join(".workspace-mgr.toml");
    let raw = std::fs::read_to_string(&path).unwrap();
    for forbidden in [
        "schema_version",
        "required_cli",
        "profile",
        "[publication]",
        "[tasks]",
        "[review]",
        "[storage]",
        "[agent]",
        "branch_prefix",
        "auto_s3_above_bytes",
    ] {
        assert!(
            !raw.contains(forbidden),
            "unexpected policy key {forbidden}"
        );
    }

    let all = workspace(&fixture.shared, ["--format", "human", "instructions"]);
    let text = String::from_utf8(all.stdout).unwrap();
    assert!(text.contains("## Mental model"));
    assert!(text.contains("## Session-wide constraints"));
    assert!(text.contains("## Find the next operation"));
    assert!(!text.contains("\n## Artifact hygiene\n"));
    assert!(!text.contains("\n## Storage placement\n"));
    assert!(!text.contains("\n## Publication\n"));

    for topic in [
        "task",
        "publish",
        "artifacts",
        "storage",
        "shared-checkout",
        "infrastructure",
    ] {
        let rendered = workspace(&fixture.shared, ["instructions", topic]);
        assert!(
            !rendered.stdout.is_empty(),
            "topic {topic} was not rendered"
        );
    }

    let task_rules = workspace(&fixture.shared, ["instructions", "task"]);
    let task_rules = String::from_utf8(task_rules.stdout).unwrap();
    assert!(task_rules.contains("default write boundary is its own task directory"));
    assert!(task_rules.contains("explicitly authorize the exact path and action"));
    assert!(task_rules.contains("they do not create authorization"));
    assert!(task_rules.contains("outside the repository is outside the task directory too"));
    assert!(task_rules.contains("own files are its durable record"));
    for organization_rule in [
        "Pending deliverable task directories must remain at the repository top level",
        "An OPEN PR means pending",
        "MERGED, CLOSED without merging, or a successful current-metadata query finding no corresponding PR means done",
        "`YYYY/<task-dir>`, `YYYYMM/<task-dir>`, and `YYYY/MM/<task-dir>`",
        "only when the user explicitly requests it",
        "through a repository-infrastructure task",
        "Never organize tasks automatically after merge or during turn-end synchronization",
        "without specifying a structure, use `YYYY/MM/<task-dir>`",
        "based on each task directory's timestamp",
    ] {
        assert!(
            task_rules.contains(organization_rule),
            "task instructions are missing {organization_rule:?}"
        );
    }
    for archive_rule in [
        "Archive queries the current task branch and compatible saved review branch hints",
        "without inspecting historical configuration, tree history, commit review coverage, or branch-tip ancestry",
        "Completion checkpoints and task upgrade are not archive prerequisites",
        "Ordinary tracked, staged, untracked, ignored, and local-only content moves unchanged",
        "runtime usability after relocation is outside archive scope",
        "no outer-tracked files or gitlinks",
        "archive never repairs them or edits external administration",
    ] {
        assert!(
            task_rules.contains(archive_rule),
            "task instructions are missing archive scope rule {archive_rule:?}"
        );
    }
    assert!(!task_rules.contains("--historical-record"));
    // A record added to a cleanup would make it growth the limit refuses, so
    // the lifecycle and hygiene rules defer it to the same publication.
    assert!(
        task_rules
            .contains("record it in the task's files in the first publication the limit allows")
    );
    assert!(task_rules.contains("Markdown files of your choosing inside the task directory"));

    let artifact_rules = workspace(&fixture.shared, ["instructions", "artifacts"]);
    let artifact_rules = String::from_utf8(artifact_rules.stdout).unwrap();
    assert!(artifact_rules.contains("Do the work inside the task directory"));
    assert!(artifact_rules.contains("a system temporary directory"));
    assert!(artifact_rules.contains("are task artifacts, not disposables"));
    assert!(artifact_rules.contains("never safely reproducible output"));
    assert!(artifact_rules.contains("record how to regenerate credentials, never the values"));
    assert!(artifact_rules.contains("Markdown files of your choosing inside the task directory"));
    assert!(artifact_rules.contains("Curate what the task publishes"));
    assert!(artifact_rules.contains(
        "publish the cleanup on its own and record the decision in the first publication the limit allows"
    ));
    assert!(artifact_rules.contains("There is no third state"));
    assert!(artifact_rules.contains("The by-products of the work are not published by default"));
    assert!(artifact_rules.contains("Ignore rules live in two layers"));
    assert!(artifact_rules.contains(".workspace-mgr/repository.gitignore"));
    assert!(artifact_rules.contains("never hand-edit the root file"));
    assert!(artifact_rules.contains("only a machine-local rule hides"));
    assert!(artifact_rules.contains("`bulk-publication` warning"));
    assert!(artifact_rules.contains("S3 is not a dumping ground"));
    assert!(
        artifact_rules
            .contains("Every nested Git repository must be ignored as an entire directory")
    );
    assert!(
        artifact_rules.contains("Plan and publish enforce this boundary before storage placement")
    );
    assert!(
        artifact_rules
            .contains("A new task-local ignore file may be carried by the same publication")
    );
    assert!(artifact_rules.contains("Never create a gitlink for a nested repository"));
    // The repository layer is a shared root path, so the curation rule and the
    // write-boundary rule have to read as one policy rather than two that
    // contradict each other.
    assert!(
        artifact_rules.contains("only one of them is inside a deliverable task's write boundary")
    );
    assert!(artifact_rules.contains("needs the user's explicit authorization"));
    // Thresholds are rendered from the constants, so this pins the numbers the
    // documents repeat as literals, in the unit the rest of the policy uses.
    assert!(
        artifact_rules.contains("more than 200 new files or more than 256 MiB (268435456 bytes)"),
        "{artifact_rules}"
    );

    let core_rules = workspace(&fixture.shared, ["instructions", "core"]);
    let core_rules = String::from_utf8(core_rules.stdout).unwrap();
    assert!(
        core_rules.contains("stops being read-only as soon as it produces something worth keeping")
    );

    let publication_rules = workspace(&fixture.shared, ["instructions", "publish"]);
    let publication_rules = String::from_utf8(publication_rules.stdout).unwrap();
    assert!(
        publication_rules
            .contains("record the turn's decisions, process, tools, and hard-to-reproduce results")
    );
    assert!(
        publication_rules
            .contains("read that plan's `changed_paths`, `ignored_paths`, and placement decisions")
    );

    let infrastructure_rules = workspace(&fixture.shared, ["instructions", "infrastructure"]);
    let infrastructure_rules = String::from_utf8(infrastructure_rules.stdout).unwrap();
    assert!(infrastructure_rules.contains("write only the declared paths"));
    assert!(infrastructure_rules.contains("separate explicit user approval"));
    assert!(infrastructure_rules.contains("shared checkout"));
    assert!(infrastructure_rules.contains("--manifest"));

    workspace(
        &fixture.shared,
        [
            "task",
            "create",
            "fixed-branch",
            "--title",
            "Fixed branch",
            "--purpose",
            "Verify the product-owned branch strategy.",
            "--timestamp",
            "20260829-170010",
        ],
    );
    let manifest = fixture
        .shared
        .join("20260829-170010-fixed-branch/.workspace-mgr-task.toml");
    let original = std::fs::read_to_string(&manifest).unwrap();
    let task = fixture.shared.join("20260829-170010-fixed-branch");
    let cases = [
        (
            original.replace("codex/fixed-branch", "codex/other-branch"),
            "task branch must be",
        ),
        (original.replace("kind = \"deliverable\"\n", ""), "kind"),
        (
            original.replace("slug = \"fixed-branch\"\n", ""),
            "lowercase kebab",
        ),
        (original.replace("title = \"Fixed branch\"\n", ""), "title"),
        (
            original.replace(
                "purpose = \"Verify the product-owned branch strategy.\"\n",
                "",
            ),
            "purpose",
        ),
        (
            original.replace(
                "additional_scopes = []\n",
                "[[additional_scopes]]\npath = \"20260829-170010-fixed-branch/nested\"\nreason = \"This is already inside the task.\"\n",
            ),
            "must not overlap",
        ),
    ];
    for (altered, expected) in cases {
        std::fs::write(&manifest, altered).unwrap();
        let rejected = workspace_unchecked(&task, ["task", "status"]);
        assert_eq!(rejected.status.code(), Some(2));
        assert!(
            String::from_utf8_lossy(&rejected.stderr).contains(expected),
            "missing {expected:?} in {}",
            String::from_utf8_lossy(&rejected.stderr)
        );
    }
    std::fs::write(&manifest, original).unwrap();
}

#[test]
fn fresh_manage_uses_native_storage_without_external_configuration_files() {
    let fixture = GitFixture::new();
    fixture.clone_shared();
    let storage = fixture.root.join("storage");
    workspace(
        &fixture.shared,
        ["manage", "--s3-url", storage.to_str().unwrap()],
    );
    let config: toml::Value = toml::from_str(
        &std::fs::read_to_string(fixture.shared.join(".workspace-mgr.toml")).unwrap(),
    )
    .unwrap();
    assert_eq!(config["minimum_cli_version"].as_str(), Some("0.8.1"));
    for path in [".dvc", ".dvcignore", ".gitattributes"] {
        assert!(
            !fixture.shared.join(path).exists(),
            "{path} should not be generated"
        );
    }
    assert!(fixture.shared.join("AGENTS.md").is_file());
    let root_ignore = std::fs::read_to_string(fixture.shared.join(".gitignore")).unwrap();
    assert!(root_ignore.contains("/.workspace-mgr/local/"));
    assert!(!root_ignore.contains(".dvc"));
}

#[test]
fn invalid_native_storage_configuration_changes_no_scaffolds() {
    let fixture = GitFixture::new();
    fixture.clone_shared();
    let root_ignore = fixture.shared.join(".gitignore");
    std::fs::write(&root_ignore, "/private/\n").unwrap();
    let rejected = workspace_unchecked(
        &fixture.shared,
        [
            "manage",
            "--s3-url",
            "s3://fixture/root",
            "--s3-endpoint-url",
            "https://user:secret@example.invalid",
        ],
    );
    assert_eq!(rejected.status.code(), Some(2));
    assert!(!fixture.shared.join("AGENTS.md").exists());
    assert!(!fixture.shared.join(".workspace-mgr.toml").exists());
    assert_eq!(
        std::fs::read_to_string(&root_ignore).unwrap(),
        "/private/\n"
    );
    assert!(
        !fixture
            .shared
            .join(".workspace-mgr/repository.gitignore")
            .exists()
    );
}

#[test]
fn tracked_configuration_rejects_credentials_and_policy_keys() {
    let fixture = GitFixture::new();
    fixture.clone_shared();
    let credentials = workspace_unchecked(
        &fixture.shared,
        [
            "manage",
            "--s3-url",
            "s3://bucket/prefix?X-Amz-Signature=tracked-secret",
            "--dry-run",
        ],
    );
    assert_eq!(credentials.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&credentials.stderr).contains("query or fragment"));
    assert!(!fixture.shared.join(".workspace-mgr.toml").exists());

    workspace(&fixture.shared, ["manage"]);
    let config_path = fixture.shared.join(".workspace-mgr.toml");
    let original = std::fs::read_to_string(&config_path).unwrap();
    for field in ["remote", "branch"] {
        let prefix = format!("{field} = ");
        let incomplete = original
            .lines()
            .filter(|line| !line.starts_with(&prefix))
            .collect::<Vec<_>>()
            .join("\n")
            + "\n";
        std::fs::write(&config_path, incomplete).unwrap();
        let rejected = workspace_unchecked(&fixture.shared, ["instructions"]);
        assert_eq!(rejected.status.code(), Some(2));
        assert!(String::from_utf8_lossy(&rejected.stderr).contains(field));
    }
    let mut config = original;
    config.push_str("\n[review]\nmanaged_by = \"agent\"\n");
    std::fs::write(&config_path, config).unwrap();
    let instructions = workspace_unchecked(&fixture.shared, ["instructions"]);
    assert_eq!(instructions.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&instructions.stderr).contains("unknown field"));
}

#[test]
fn native_storage_location_is_authoritative_and_cannot_move_with_boundaries() {
    let fixture = GitFixture::new();
    fixture.clone_shared();
    let remote = fixture.root.join("storage");
    workspace(
        &fixture.shared,
        ["manage", "--s3-url", remote.to_str().unwrap()],
    );
    let config_path = fixture.shared.join(".workspace-mgr.toml");
    let public_config = std::fs::read_to_string(&config_path).unwrap();
    git(&fixture.shared, ["add", "-A"]);
    git(&fixture.shared, ["commit", "-m", "Manage native storage"]);
    let pointer = fixture.shared.join("retained.bin.wm-storage.json");
    std::fs::write(
        &pointer,
        r#"{
        "schema_version": 1,
        "path": "retained.bin",
        "kind": "file",
        "checksum": {"algorithm": "md5", "digest": "d41d8cd98f00b204e9800998ecf8427e"},
        "size": 0
    }"#,
    )
    .unwrap();
    let relocated = public_config.replace(
        remote.to_str().unwrap(),
        fixture.root.join("other-storage").to_str().unwrap(),
    );
    std::fs::write(&config_path, relocated).unwrap();
    let rejected_relocation = workspace_unchecked(&fixture.shared, ["manage"]);
    assert_eq!(rejected_relocation.status.code(), Some(2));
    assert!(
        String::from_utf8_lossy(&rejected_relocation.stderr)
            .contains("cannot change the managed S3 location")
    );

    std::fs::write(&config_path, &public_config).unwrap();
    assert_eq!(
        json(&workspace(&fixture.shared, ["manage"]))["status"],
        "no_changes"
    );
    let mut config: toml::Value = toml::from_str(&public_config).unwrap();
    config.as_table_mut().unwrap().remove("s3");
    std::fs::write(&config_path, toml::to_string_pretty(&config).unwrap()).unwrap();
    let refused = workspace_unchecked(&fixture.shared, ["manage"]);
    assert_eq!(refused.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&refused.stderr).contains("cannot disable managed S3"));
    std::fs::remove_file(&pointer).unwrap();
    workspace(&fixture.shared, ["manage"]);
    assert!(!fixture.shared.join(".dvc").exists());
}

#[test]
fn manage_generates_the_root_ignore_file_from_the_repository_module() {
    let fixture = GitFixture::new();
    fixture.clone_shared();
    workspace(&fixture.shared, ["manage"]);
    let root_ignore = fixture.shared.join(".gitignore");
    let product_only = std::fs::read_to_string(&root_ignore).unwrap();
    assert!(
        !product_only.contains("# Repository rules imported"),
        "an absent module must not leave an empty import section: {product_only}"
    );
    assert_eq!(
        json(&workspace(&fixture.shared, ["manage"]))["status"],
        "no_changes"
    );

    std::fs::create_dir_all(fixture.shared.join(".workspace-mgr")).unwrap();
    std::fs::write(
        fixture.shared.join(".workspace-mgr/repository.gitignore"),
        "/vendor/\n*.bak\n",
    )
    .unwrap();

    let imported = workspace(&fixture.shared, ["manage"]);
    let imported = json(&imported);
    assert_eq!(imported["status"], "managed");
    assert!(
        imported["actions"]
            .as_array()
            .unwrap()
            .iter()
            .any(|action| action["path"] == ".gitignore" && action["action"] == "update"),
        "{imported}"
    );
    let with_module = std::fs::read_to_string(&root_ignore).unwrap();
    assert!(with_module.contains(
        "\n# Repository rules imported from .workspace-mgr/repository.gitignore.\n/vendor/\n*.bak\n"
    ));
    assert!(with_module.find(".DS_Store").unwrap() < with_module.find("/vendor/").unwrap());
    assert!(
        git(&fixture.shared, ["check-ignore", "--", "vendor/thing.txt"])
            .status
            .success()
    );
    assert_eq!(
        json(&workspace(&fixture.shared, ["manage"]))["status"],
        "no_changes"
    );

    // A hand edit of a product-owned file is drift, not content to merge.
    std::fs::write(
        &root_ignore,
        format!("{with_module}# locally edited\n/only-my-rule\n"),
    )
    .unwrap();
    let unhealthy = workspace_unchecked(&fixture.shared, ["doctor"]);
    assert_eq!(unhealthy.status.code(), Some(2));
    assert!(
        json(&unhealthy)["checks"]
            .as_array()
            .unwrap()
            .iter()
            .any(|check| {
                check["name"] == "repository-scaffold"
                    && check["status"] == "error"
                    && check["detail"].as_str().unwrap().contains(".gitignore")
            })
    );

    let repaired = workspace(&fixture.shared, ["manage"]);
    assert_eq!(json(&repaired)["status"], "managed");
    assert_eq!(std::fs::read_to_string(&root_ignore).unwrap(), with_module);
    assert_eq!(
        json(&workspace(&fixture.shared, ["doctor"]))["status"],
        "ok"
    );
}

#[test]
fn first_manage_preserves_existing_root_ignore_rules_without_manual_steps() {
    let fixture = GitFixture::new();
    fixture.clone_shared();
    let root_ignore = fixture.shared.join(".gitignore");
    let module = fixture.shared.join(".workspace-mgr/repository.gitignore");
    let existing = "/build\n*.log\n!keep.log\n";
    std::fs::write(&root_ignore, existing).unwrap();
    let dry_run = workspace(&fixture.shared, ["manage", "--dry-run"]);
    assert_eq!(json(&dry_run)["status"], "dry_run");
    assert_eq!(std::fs::read_to_string(&root_ignore).unwrap(), existing);
    assert!(!module.exists());
    assert!(!fixture.shared.join(".workspace-mgr.toml").exists());
    workspace(&fixture.shared, ["manage"]);
    assert_eq!(std::fs::read_to_string(&module).unwrap(), existing);
    let generated = std::fs::read_to_string(&root_ignore).unwrap();
    assert!(generated.starts_with("# Generated by workspace-mgr."));
    assert!(generated.contains(existing));
    assert_eq!(
        json(&workspace(&fixture.shared, ["manage"]))["status"],
        "no_changes"
    );
}

#[test]
fn scaffold_reconciliation_preserves_a_managed_local_only_block() {
    let fixture = GitFixture::new();
    workspace(&fixture.seed, ["manage"]);
    fixture.commit_seed("Initialize workspace");
    fixture.clone_shared();
    workspace(
        &fixture.shared,
        [
            "task",
            "create",
            "local-block",
            "--title",
            "Local block",
            "--purpose",
            "Keep a managed local-only rule across reconciliation.",
            "--timestamp",
            "20260829-171500",
        ],
    );
    let task = fixture.shared.join("20260829-171500-local-block");
    std::fs::write(task.join("data.bin"), b"local bytes").unwrap();
    workspace(&task, ["untrack", "20260829-171500-local-block/data.bin"]);

    // Take the block exactly as `untrack` writes it, so this fixture cannot
    // drift from the real writer's format.
    let written = std::fs::read_to_string(task.join(".gitignore")).unwrap();
    let begin = written.find("# workspace-mgr local begin").unwrap();
    let block = format!("\n{}", &written[begin..]);
    let root_ignore = fixture.shared.join(".gitignore");
    let generated = std::fs::read_to_string(&root_ignore).unwrap();
    std::fs::write(&root_ignore, format!("{generated}{block}")).unwrap();
    assert_eq!(
        json(&workspace(&fixture.shared, ["doctor"]))["status"],
        "ok"
    );

    // Drift elsewhere in the file is repaired while the block survives.
    std::fs::write(
        &root_ignore,
        format!("{generated}# hand edited\n/stale{block}"),
    )
    .unwrap();
    let repaired = workspace(&fixture.shared, ["manage"]);
    assert_eq!(json(&repaired)["status"], "managed");
    let reconciled = std::fs::read_to_string(&root_ignore).unwrap();
    assert!(!reconciled.contains("/stale"), "{reconciled}");
    assert!(reconciled.contains(".DS_Store"));
    assert!(reconciled.ends_with(&block), "{reconciled}");
    assert_eq!(
        json(&workspace(&fixture.shared, ["doctor"]))["status"],
        "ok"
    );

    // A marker without its partner has no readable extent. Refusing it would
    // wedge the one file the product can always rebuild, so regeneration drops
    // it and the report says which marker it dropped.
    std::fs::write(
        &root_ignore,
        format!("{generated}\n# workspace-mgr local begin 6461746162696e\n/data.bin\n"),
    )
    .unwrap();
    let repaired = workspace(&fixture.shared, ["manage"]);
    let repaired = json(&repaired);
    assert_eq!(repaired["status"], "managed");
    let detail = repaired["actions"]
        .as_array()
        .unwrap()
        .iter()
        .find(|action| action["path"] == ".gitignore")
        .unwrap_or_else(|| panic!("{repaired}"))["detail"]
        .as_str()
        .unwrap()
        .to_owned();
    assert!(
        detail.contains("dropped 1 unpaired managed local-only block marker")
            && detail.contains("# workspace-mgr local begin 6461746162696e"),
        "{detail}"
    );
    assert_eq!(std::fs::read_to_string(&root_ignore).unwrap(), generated);
    assert_eq!(
        json(&workspace(&fixture.shared, ["doctor"]))["status"],
        "ok"
    );
    assert_eq!(
        json(&workspace(&fixture.shared, ["manage"]))["status"],
        "no_changes"
    );
}

#[test]
fn an_already_managed_repository_preserves_new_root_rules_and_existing_module_rules() {
    let fixture = GitFixture::new();
    fixture.clone_shared();
    workspace(&fixture.shared, ["manage"]);
    let root_ignore = fixture.shared.join(".gitignore");
    let module = fixture.shared.join(".workspace-mgr/repository.gitignore");
    std::fs::write(&module, "/existing-private/\n").unwrap();
    let repository_rules = "/secrets.env\n/vendor/\n*.log\n!keep.log\n";
    std::fs::write(&root_ignore, repository_rules).unwrap();
    let unhealthy = workspace_unchecked(&fixture.shared, ["doctor"]);
    assert_eq!(unhealthy.status.code(), Some(2));
    assert!(
        json(&unhealthy)["checks"]
            .as_array()
            .unwrap()
            .iter()
            .any(|check| {
                check["name"] == "repository-scaffold"
                    && check["detail"]
                        .as_str()
                        .unwrap()
                        .contains("workspace-mgr manage")
            })
    );
    workspace(&fixture.shared, ["manage"]);
    assert_eq!(
        std::fs::read_to_string(&module).unwrap(),
        format!("/existing-private/\n\n{repository_rules}")
    );
    let regenerated = std::fs::read_to_string(&root_ignore).unwrap();
    for rule in [
        "/existing-private/",
        "/secrets.env",
        "/vendor/",
        "*.log",
        "!keep.log",
    ] {
        assert!(regenerated.contains(rule), "{rule} was discarded");
    }
    assert_eq!(
        json(&workspace(&fixture.shared, ["doctor"]))["status"],
        "ok"
    );
    assert_eq!(
        json(&workspace(&fixture.shared, ["manage"]))["status"],
        "no_changes"
    );
}

#[test]
fn a_symlinked_root_ignore_file_is_refused_with_the_migration_it_needs() {
    let fixture = GitFixture::new();
    fixture.clone_shared();
    std::fs::write(fixture.shared.join("shared-rules.txt"), "/vendor/\n").unwrap();
    std::os::unix::fs::symlink("shared-rules.txt", fixture.shared.join(".gitignore")).unwrap();

    let refused = workspace_unchecked(&fixture.shared, ["manage"]);

    assert_eq!(refused.status.code(), Some(2));
    let stderr = String::from_utf8_lossy(&refused.stderr).into_owned();
    assert!(stderr.contains("may not traverse a symlink"), "{stderr}");
    assert!(
        stderr.contains(".workspace-mgr/repository.gitignore"),
        "the symlink refusal must still name the migration: {stderr}"
    );
}

#[test]
fn a_repository_module_may_not_carry_the_products_own_block_markers() {
    // Regeneration harvests these markers back out of the file it writes, so a
    // module that carried one would append its block again on every `manage` and
    // the file would never settle.
    let fixture = GitFixture::new();
    fixture.clone_shared();
    std::fs::create_dir_all(fixture.shared.join(".workspace-mgr")).unwrap();
    std::fs::write(
        fixture.shared.join(".workspace-mgr/repository.gitignore"),
        "/vendor/\n# workspace-mgr local begin 6161\n/aa\n# workspace-mgr local end 6161\n",
    )
    .unwrap();

    let refused = workspace_unchecked(&fixture.shared, ["manage"]);

    assert_eq!(refused.status.code(), Some(2));
    let stderr = String::from_utf8_lossy(&refused.stderr).into_owned();
    assert!(stderr.contains("managed block markers"), "{stderr}");
    assert!(!fixture.shared.join(".gitignore").exists());
}

#[test]
fn global_instructions_index_repository_policy_without_leaking_its_body() {
    let fixture = GitFixture::new();
    fixture.clone_shared();
    workspace(&fixture.shared, ["manage"]);
    let module = fixture
        .shared
        .join(".workspace-mgr/instructions/repository.md");
    std::fs::create_dir_all(module.parent().unwrap()).unwrap();
    let first = "  User-owned specific procedure: keep exact spacing.\n\n";
    std::fs::write(&module, first).unwrap();
    let all = json(&workspace(
        &fixture.shared,
        ["--format", "json", "instructions"],
    ));
    let markdown = all["markdown"].as_str().unwrap();
    assert!(markdown.contains("workspace-mgr instructions repository"));
    assert!(markdown.contains("Read it before task work"));
    assert!(!markdown.contains("keep exact spacing"));
    let detailed = json(&workspace(
        &fixture.shared,
        ["--format", "json", "instructions", "repository"],
    ));
    assert!(detailed["markdown"].as_str().unwrap().contains(first));
    let next = "Changed user-owned procedure, not product policy.\n";
    std::fs::write(&module, next).unwrap();
    let changed = json(&workspace(
        &fixture.shared,
        ["--format", "json", "instructions", "all"],
    ));
    assert_ne!(all["policy_hash"], changed["policy_hash"]);
    assert!(!changed["markdown"].as_str().unwrap().contains(next));
    let explicit = json(&workspace(
        &fixture.shared,
        ["--format", "json", "instructions", "repository"],
    ));
    assert!(explicit["markdown"].as_str().unwrap().contains(next));
}
