use std::fs;

use serde::Serialize;
use sha2::{Digest, Sha256};

use crate::config::{
    Config, MergeAuthority, Profile, PullRequestPolicy, PullRequestState, ReviewManager,
};
use crate::error::{Error, IoContext, Result};
use crate::git::GitRepo;
use crate::path::reject_symlink_traversal;

pub const BOOTSTRAP: &str = "# Repository instructions\n\nBefore doing any repository work, run:\n\n    workspace-mgr instructions --repo .\n\nFollow its output as the repository instructions for this session. If the command\nis unavailable or fails, stop and report the problem. Do not substitute lower-level\nversion-control or storage mutation commands.\n";
pub const MANAGEMENT_MODEL: &str = include_str!("../docs/management-model.md");

#[derive(Debug, Clone, Serialize)]
pub struct InstructionDocument {
    pub cli_version: String,
    pub schema_version: u32,
    pub policy_hash: String,
    pub topic: String,
    pub markdown: String,
}

pub fn render(repo: &GitRepo, config: &Config, topic: Option<&str>) -> Result<InstructionDocument> {
    let topic = topic.unwrap_or("all");
    let valid_topics = [
        "all",
        "model",
        "core",
        "task",
        "publish",
        "artifacts",
        "storage",
        "shared-checkout",
        "infrastructure",
    ];
    if !valid_topics.contains(&topic) {
        return Err(Error::message(format!(
            "unknown instruction topic {topic:?}; expected one of {}",
            valid_topics.join(", ")
        )));
    }

    let mut sections = Vec::new();
    if topic == "all" || topic == "model" {
        sections.push(MANAGEMENT_MODEL.trim().to_owned());
    }

    if topic != "model" {
        sections.push(format!(
            "# Effective repository instructions\n\nGenerated by `workspace-mgr {}` from `{}`. These instructions apply to this repository for the current session. Explicit user directions can authorize a narrow exception; record the exact scope and do not broaden it.",
            env!("CARGO_PKG_VERSION"),
            crate::config::CONFIG_NAME
        ));
    }

    if topic == "all" || topic == "core" {
        sections.push(core_section());
    }
    if include_module(config, topic, "task", "scope")? {
        sections.push(task_section(config));
    }
    if include_module(config, topic, "publish", "publication")? {
        sections.push(publication_section(config));
    }
    if include_module(config, topic, "artifacts", "artifact-hygiene")? {
        sections.push(artifact_hygiene_section());
    }
    if include_module(config, topic, "storage", "storage")? {
        sections.push(storage_section(config));
    }
    if include_module(config, topic, "shared-checkout", "shared-checkout")? {
        sections.push(shared_checkout_section(config));
    }
    if include_module(config, topic, "infrastructure", "infrastructure")? {
        sections.push(infrastructure_section());
    }
    if topic == "all" {
        let extra = repo.root.join(".workspace-mgr/instructions/repository.md");
        reject_symlink_traversal(
            &repo.root,
            ".workspace-mgr/instructions/repository.md",
            "repository instruction module",
        )?;
        if extra.is_file() {
            let content = fs::read_to_string(&extra).at(&extra)?;
            if content.len() > 65_536 {
                return Err(Error::message(format!(
                    "repository instruction module exceeds 64 KiB: {}",
                    extra.display()
                )));
            }
            if !content.trim().is_empty() {
                sections.push(format!(
                    "# Repository-specific additions\n\n{}",
                    content.trim()
                ));
            }
        }
    }

    let body = sections.join("\n\n");
    let mut hasher = Sha256::new();
    hasher.update(env!("CARGO_PKG_VERSION"));
    hasher.update(config.render()?);
    hasher.update(topic);
    hasher.update(&body);
    let policy_hash = format!("{:x}", hasher.finalize());
    let markdown = format!(
        "<!-- workspace-mgr: cli={} schema={} policy={} topic={} -->\n{}\n",
        env!("CARGO_PKG_VERSION"),
        config.schema_version,
        &policy_hash[..16],
        topic,
        body
    );
    Ok(InstructionDocument {
        cli_version: env!("CARGO_PKG_VERSION").to_owned(),
        schema_version: config.schema_version,
        policy_hash,
        topic: topic.to_owned(),
        markdown,
    })
}

fn include_module(config: &Config, topic: &str, topic_name: &str, module: &str) -> Result<bool> {
    let enabled = config.agent.modules.iter().any(|item| item == module);
    if topic == topic_name && !enabled {
        return Err(Error::message(format!(
            "instruction topic {topic_name:?} is disabled; enable agent module {module:?} in {}",
            crate::config::CONFIG_NAME
        )));
    }
    Ok(enabled && (topic == "all" || topic == topic_name))
}

fn core_section() -> String {
    "## Operating model\n\n- Read-only requests do not require a task directory.\n- User authorization overrides repository defaults only for the requested paths and actions; higher-priority safety and platform rules still apply.\n- `workspace-mgr` is the only repository-content mutation interface. Treat a refusal as a guard to investigate, not a reason to bypass it with lower-level Git or storage tools. Repository-hosting review metadata remains an agent or user responsibility when the review policy below requires it.\n- Run `workspace-mgr doctor` when configuration, dependencies, or repository state appears inconsistent."
        .to_owned()
}

fn task_section(config: &Config) -> String {
    format!(
        "## Task lifecycle\n\n- Create ordinary writable work with `workspace-mgr task create <slug> --title <title> --purpose <purpose>`. Create repository-wide work with `workspace-mgr task create <slug> --kind infrastructure --title <title> --purpose <purpose> --scope <path> --scope-note <reason>`.\n- Deliverable task directories follow `{}`. Infrastructure tasks use a private manifest and isolated worktree instead of a repository task directory. Both use branches prefixed with `{}`.\n- Reuse the same task for the full conversation or work item. Do not write into another active task without explicit authorization.\n- Keep a deliverable task README concise and current. It describes purpose and outputs, and includes a `## Directory map`; it is not a chronological log.\n- The task manifest is the authoritative task scope. Additional repository paths require a concise authorization reason.\n- Use `workspace-mgr task status` to inspect the resolved task before publishing.",
        config.tasks.directory_pattern, config.publication.branch_prefix
    )
}

fn publication_section(config: &Config) -> String {
    let review = review_section(config);
    format!(
        "## Publication\n\n- Run `workspace-mgr plan` before publication. A plan may inspect remote metadata but does not create a revision, upload stored data, or publish a branch.\n- Run `workspace-mgr publish -m <message>` to publish only the declared scopes to the configured target branch.\n- Do not interpret a lower-level status command as the complete task state; use the task-targeted plan.\n- Verify the reported revision, remote revision, and a final no-change plan before claiming repository content is current.\n- `{}` is the configured base branch on remote `{}`.\n\n{review}",
        config.publication.base_branch, config.publication.remote
    )
}

fn review_section(config: &Config) -> String {
    if config.review.pull_request == PullRequestPolicy::Disabled {
        return "## Pull request responsibility\n\n- This repository disables pull requests for workspace-mgr tasks. Do not create one unless the user explicitly overrides this policy. `workspace-mgr` still publishes and verifies the task branch."
            .to_owned();
    }
    let (requirement, creation) = match config.review.pull_request {
        PullRequestPolicy::Required => (
            "A task is not fully synchronized until its one matching pull request is current.",
            "After the first successful publish",
        ),
        PullRequestPolicy::Optional => (
            "Create a pull request when the user or repository workflow requests review.",
            "When review is requested after a successful publish",
        ),
        PullRequestPolicy::Disabled => unreachable!(),
    };
    let state = match config.review.initial_state {
        PullRequestState::Draft => "draft",
        PullRequestState::Ready => "ready for review",
    };
    let management = match config.review.managed_by {
        ReviewManager::Agent => format!(
            "- {creation}, the agent must query the hosting provider for the task's head branch. Reuse its existing open pull request or create exactly one {state} pull request; never create a duplicate.\n- The agent owns the pull-request title and living description. Keep them aligned with the current goal, declared scope, important deliverables, validation evidence, and known limitations. Update them after every materially changed publication.\n- After creating or updating the pull request, verify that it is open, its base and head branches are correct, its review state is `{state}`, and its head revision equals the remote revision reported by `workspace-mgr publish`."
        ),
        ReviewManager::User => "- The user manages pull-request creation and metadata. The agent must report the verified remote, base branch, head branch, revision, scope, and validation handoff without creating or editing a pull request."
            .to_owned(),
    };
    let merge = match config.review.merge_authority {
        MergeAuthority::User => {
            "- The agent must not merge, enable auto-merge, approve, close, or change a draft pull request to ready. Those transitions belong to the user or maintainer unless the user explicitly overrides this repository policy."
        }
        MergeAuthority::Agent => {
            "- The agent may perform merge-state transitions only when the user explicitly requests them and repository review conditions are satisfied."
        }
    };
    format!(
        "## Pull request responsibility\n\n- `workspace-mgr` publishes and verifies repository state but never calls a hosting-provider API. Pull-request operations are a separate agent or user responsibility.\n- {requirement}\n{management}\n- If hosting authentication, permissions, connectivity, or metadata verification fails, report the blocker immediately and do not claim the task is fully synchronized.\n{merge}"
    )
}

fn artifact_hygiene_section() -> String {
    "## Artifact hygiene\n\n- Keep every eligible task-owned input, deliverable, and reproducibility artifact in the declared scope.\n- Before publication, identify external Git checkouts, generated build output, and retained large content.\n- Ignore safely reproducible output and external nested repositories using the narrowest applicable rule.\n- Never flatten a nested repository into the parent repository or create a gitlink unless explicitly requested.\n- Choose retained-content placement through `workspace-mgr storage`; do not introduce another large-file mechanism.\n- Keep credentials and private runtime configuration out of tracked files and command output."
        .to_owned()
}

fn storage_section(config: &Config) -> String {
    let s3_note = if config.storage.requires_object_versioning() {
        "S3 is configured. The bucket must have object versioning enabled; exact object versions are verified before the Git revision is published."
    } else if config.storage.s3_enabled() {
        "An S3-compatible test or local storage adapter is configured; remote presence is verified before the Git revision is published."
    } else {
        "S3 is not configured, so paths may only be placed in Git until repository configuration is updated."
    };
    format!(
        "## Storage placement\n\n- Every retained path is stored either directly in Git or as versioned content in S3. `workspace-mgr` owns the underlying mechanics; do not invoke lower-level storage tools.\n- Use `workspace-mgr storage status [<path> ...]` to inspect effective placement and whether it came from an explicit choice, existing history, or automatic policy.\n- Use `workspace-mgr storage set <path> --to git|s3 --reason <reason>` when placement must be explicit. This is valid in either direction regardless of file size.\n- Use `workspace-mgr storage reset <path>` to remove an explicit choice and reapply automatic policy. In automatic mode, previously published placement stays stable; new retained files above {} bytes go to S3 and smaller files go to Git.\n- Placement changes, resets, and `workspace-mgr move <old> <new>` update local desired state only. `workspace-mgr publish` is the only command that writes to Git or S3 remotes.\n- Use `workspace-mgr storage hydrate [<path> ...]` to materialize S3 content locally without publishing. Never hand-edit or directly delete workspace-mgr storage metadata.\n- Storage credentials stay outside tracked repository configuration. Never print, copy, or commit credentials.\n- {s3_note}\n- Never request permanent remote or cache garbage collection without explicit authorization for shared-data deletion.",
        config.storage.auto_s3_above_bytes
    )
}

fn shared_checkout_section(config: &Config) -> String {
    match config.profile {
        Profile::SharedCheckout => format!(
            "## Shared checkout\n\n- Keep the shared checkout on `{}` and publish task branches without switching it.\n- Preserve unrelated working-tree overlays. Do not use broad stash, clean, reset, or deletion operations.\n- After a task is merged, use `workspace-mgr refresh`; an ordinary pull may conflict with active overlays.",
            config.publication.shared_checkout_branch
        ),
        Profile::Standard => "## Shared checkout\n\n- This repository uses the standard checkout profile, so shared-checkout publication and refresh rules are not active. Preserve unrelated working-tree changes and use the repository's normal branch-update workflow."
            .to_owned(),
    }
}

fn infrastructure_section() -> String {
    "## Repository infrastructure\n\n- Treat a change to shared policy, root entrypoints, CI, or repository-wide storage configuration as one infrastructure task with one target branch and one pull request when review policy requires it.\n- Create it with `workspace-mgr task create <slug> --kind infrastructure --title <title> --purpose <purpose> --scope <path> --scope-note <reason>`. Repeat `--scope` for every authorized shared path.\n- Work only in the isolated worktree returned by the command. An infrastructure task has private task metadata and no timestamped repository task directory.\n- Run task, storage, plan, and publish commands from that worktree. Do not add unrelated deliverable paths to its declared infrastructure scope.\n- Infrastructure storage tests use fresh temporary repositories and local or mock remotes. They must not read user cloud credentials or contact a real storage service."
        .to_owned()
}
